companieshouse/styleguides

gitignore/maven
- Added *.jar and *.zip to the maven gitignore list
=> Update maven gitignore list

perl.md
=> Fix spelling

perl.md
Moving back to agreed on Pascal module naming convention
=> Pascal case for classes

README.md, maven.md
Add a template pom.xml for Maven based projects
=> Add Maven pom.xml template

maven.md
Update maven.md replacing instances of MAVEN_REPOSITORY_HOST_URL with
MAVEN_REPOSITORY_URL inline with variable name changes
Resolves: DVOP-23
=> Update example configuration inline with changes elsewhere

README.md, jsp.md
Add some guidance on use of CFF tag ajaxAction to avoid issues in future.
=> Add some JSP guidance

makefiles.md
Update Makefile example to resolve test dependencies recursively, without needing to include specific dependencies
=> Update Makefile example

bash.md
Update the guide giving specific examples rather than just external links
Resolves: DVOP-396
=> Initial commit of bash guide

README.md, accessibility.md
Added a link to a new page about accessibility standards, with links to WCAG and GOV.UK
=> Added information about accessibility standards

java.md
Remove double word `by` and add full stop
=> Remove doubled word

git.md, git/branches.md
=> Add branch naming standards

README.md, terraform.md
=> Initial commit of Terraform style guide

Makefiles/go_makefiles.md
Update the makefile to include go mod tidy
=> Update the makefile to include go mod tidy

health_check.md
Initial idea for health check guidelines.
=> Adding health check guidelines

terraform.md
Some updates and guidance following this [PR](https://github.com/companieshouse/test-data-generator-stack/pull/2)
Relates to DVOP-902
=> Guidance for variable assignments in Terraform

logging.md
Add standards for logging from applications.
* Best practises
* Useful information to log
* Things which must not be logged
* Things to avoid
=> Add logging standards

README.md, language_common.md, makefiles.md
Add common language standards so that they are available for use as part of reviews. 
Also create a missing markdown file for makefiles
=> Add common language standards

README.md
Add link to health_check.md from main readme
=> Add link to health_check.md

README.md, feature_flag.md
Added some basic guidelines for feature flagging for reference.
=> Added some initial feature flag standards

environment_variables.md
Add guidance on using application.properties for Java Spring projects as suggested by @SteveHicksCH
=> Add guidance on using application.properties for Java Spring projects

feature_flag.md
* Moved content from Confluence into the style guide
* Added a recommendation around use of a prefix
=> Update to feature flag guidelines

java.md
Removed the element around readability so that it doesn't prevent auto-formatting from occurring where people would like to benefit from that.
=> Amended wording to remove the anything that could cause ambiguity

java.md
Add link to checkstyle config in new Artifactory so they can be found easily
=> Add link to checkstyle config in new Artifactory

terraform.md
Added detail around Data Sources
=> Update Terraform Styleguide

READMEs.md
Add standard sub-README files as suggested by @sbasile-ch to make it easier to find
=> Standard sub READMEs

README.md, READMEs.md, accessibility.md
Updates as discussed at call on 7 Sept
[ReadMe](https://github.com/companieshouse/styleguides/blob/ddcd6f0bb175431192c6b7d394ee6f95949a2835/README.md) - index of other md files updated
[ReadMes](https://github.com/companieshouse/styleguides/blob/e902c3032e7b109137890393e6b3cc6ea5c43504/READMEs.md) - text re-written
[Accessibility](https://github.com/companieshouse/styleguides/commit/125f47b9c3bac63ae4aaf320566577411adf1a63) - rewritten and further links included,
Confluence pages will be archived
=> Doc update/read me improvements

library_help.md
Adding baseline library help and instructions for deciding if a library is fit for use in CH.
=> Adding library help and instructions

README.md
Add Confluence link to Which Software Version should I use? page
=> Update README.md SW version link

accessibility.md
Links are no longer version specific
=> Update accessibility.md for WCAG 2.2

java.md
Add link to CHIPS specific guidance from java.md so that it easier to find.
=> Add link to CHIPS specific guidance from java.md

java.md
Amended Java line length to be 130 characters
=> Amended Java line length to be 130 characters
